### ISSUE TITLE
Header-only ... but papi dependency ?

### ISSUE THREAD

**Issue by eddelbuettel** [david-grs/geiger#1]
It appears that geiger is header-only as promised but then has dependencies on
- gtest for its own unit tests (fair enough, we can live with this)
- papi for its actual operations :-/

Any interest in making that optional?

**Comment by david-grs** [comment]
Well, you get some benefits from a header-only library even if it isn't dependency-free. PAPI is the reference when it is about using hardware counters and is packaged and distributed on every Linux distribution I know, so it shouldn't be an issue.

On the other side, I already thought for quite some time to make PAPI optional (it was in the TODO :)). I just did the changes and pushed them to master.

**Comment by eddelbuettel** [comment]
Nice. I'll take a look.

I was basically looking for something lightweight and easy-to-use for benchmarking in the hybrid 'C++ from R' case I use quite a bit.  In that world, deployment on Mac and Windoze is more common than my Linux use case, so loosening the papi depends would help.

**Comment by eddelbuettel** [comment]
Thumbs-up -- works great.
